# Generated by Django 4.2.7 on 2023-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atmos',
            fields=[
                ('alt', models.FloatField(primary_key=True, serialize=False)),
                ('T0', models.FloatField(default=288.15)),
                ('P0', models.FloatField(default=101325.0)),
                ('rho0', models.FloatField(default=1.22)),
                ('a0', models.FloatField(default=340.2939)),
            ],
        ),
        migrations.CreateModel(
            name='motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('d0', models.FloatField()),
                ('d1', models.FloatField()),
                ('d2', models.FloatField()),
                ('d3', models.FloatField()),
                ('d4', models.FloatField()),
                ('d5', models.FloatField()),
                ('d6', models.FloatField()),
                ('d7', models.FloatField()),
                ('d8', models.FloatField()),
                ('d9', models.FloatField()),
                ('lenght', models.FloatField()),
                ('speed_in_combustion', models.FloatField()),
                ('choked', models.BooleanField()),
            ],
        ),
    ]
